version: "3"

services:
  go:
    build: # Use the Dockerfile from the current directory to build container.
      context: .
    container_name: cakestore
    ports:
      - "3030:3030"
    depends_on:
      - "db"

  db:
    image: mysql:latest # use latest version of mysql
    container_name: database # add a name for the container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment: # add default values, see docs for more info.
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: cakestoreDB # create this database on startup
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "3306:3306"

  migrate:
    image: migrate/migrate

    volumes:
      - .:/migrations
    command:
      [
        "-path",
        "src/database/migration",
        "-database",
        "mysql://root:password@tcp(database:3306)/cakestoreDB",
        "up",
        "3",
      ]
    links:
      - db
networks:
  backend:
    external:
      name: testnet

volumes: # add volume to persist data.
  my-db:
