version: "3"

services:
  go:
    build: # Use the Dockerfile from the current directory to build container.
      context: .
    container_name: cakeTest
    ports:
      - "8081:8081"
    depends_on:
      - "db"

  db:
    image: mysql:latest # use latest version of mysql
    container_name: godockerDB # add a name for the container
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment: # add default values, see docs for more info.
      MYSQL_USER: docker
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: cakestoreDB # create this database on startup
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "3307:3307"

  migrate:
    image: migrate/migrate

    volumes:
      - .:/migrations
    command:
      [
        "-path",
        "src/database/migration",
        "-database",
        "mysql://root:@tcp(localhost:3306)/cakestoreDB",
        "up",
        "3",
      ]
    links:
      - db

volumes: # add volume to persist data.
  my-db:
